#!/bin/bash

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.1/manifest-tool-linux-amd64
chmod u+x manifest-tool
./manifest-tool push from-spec multi-arch-manifests.yaml